
dist: xenial
language:
- cpp

before_install:
- pip install --user cpp-coveralls

addons:
  sonarcloud:
     organization: nouname-github

script:
- qmake
- make
- ./tests/tests

after_success:
- coveralls —root . -E ".*external.*" -E ".*tests.*"
- build-wrapper-linux-x86-64 --out-dir bw-output make clean all
- sonar-scanner \
-D"sonar.projectKey=nouname_Lab.1" \
-D"sonar.organization=nouname-github" \
-D"sonar.sources=." \
-D"sonar.cfamily.build-wrapper-output=bw-output" \
-D"sonar.host.url=https://sonarcloud.io" \
-D"sonar.login=ccdedb6e9dc0a1070d655605dbc8a056579b3cb2"

cache:
directories:
- '$HOME/.sonar/cache'


notifications:
  email: false
