
dist: xenial
language:
- cpp

before_install:
- pip install --user cpp-coveralls

addons:
  sonarcloud:
     organization: nouname-github

script:
- qmake
- make
- ./tests/tests

after_success:
- coveralls —root . -E ".*external.*" -E ".*tests.*"
- build-wrapper-linux-x86-64 --out-dir bw-output make clean all
- sonar-scanner \
  -Dsonar.projectKey=nouname_Lab.1 \
  -Dsonar.organization=nouname-github \
  -Dsonar.sources=. \
  -Dsonar.cfamily.build-wrapper-output=bw-output \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=1194e633516e94d838fc0eaf03a8834670f7a004

cache:
directories:
- '$HOME/.sonar/cache'


notifications:
  email: false
